import Head from 'next/head'
import Image from 'next/image'
import Avater from '../components/Avater'
import styles from '../styles/Home.module.css'
import { MicrophoneIcon, SearchIcon, ViewGridIcon } from '@heroicons/react/solid'
import Footer from '../components/Footer'
import { useRef } from 'react'
import {useRouter} from 'next/router';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = e =>{
    e.preventDefault();
    const term = searchInputRef.current.value

    if(!term) return;
    router.push(`/search?term=${term}`);
  };


  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google - 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex  justify-between p-5 w-full text-sm text-gray-700 hover:text-black  '>
        {/* left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* right */}

        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* Icons */}
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-green-300 cursor-pointer' />



          <Avater url="https://th.bing.com/th/id/OIP.BK0uNDyYSQRsZwmpAFB39QHaHa?w=173&h=180&c=7&r=0&o=5&pid=1.7"/>
        </div>
        
      </header>


      {/* Body */}
      <form className='flex flex-col items-center mt-44 flex-grow w-4/5' >
        <Image 
        src="https://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
        height={100} width={300}/>

        <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-3xl'>

          <SearchIcon className='h-5 mr-3 text-gray-500 '/>
          <input ref={searchInputRef} type="text" className='flex-grow focus:outline-none' />
          <MicrophoneIcon className='h-5 '/>

        </div>

        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Google Search</button>

          <button onClick={search} className='btn'>I'm Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */}
      <Footer/>


     
    </div>
  )
}
